(cl:defpackage jetson-msg
  (:use )
  (:export
   "<AMS_STATE>"
   "AMS_STATE"
   "<ACOUSTICS_MSG>"
   "ACOUSTICS_MSG"
   "<DETECT_DOCK_FLING>"
   "DETECT_DOCK_FLING"
   "<NED_OBJECTS>"
   "NED_OBJECTS"
   "<NED_WAYPOINTS>"
   "NED_WAYPOINTS"
   "<CONTROL_EFFORTS>"
   "CONTROL_EFFORTS"
   "<MOTORSTATUS_MSG>"
   "MOTORSTATUS_MSG"
   "<STATE_MSG>"
   "STATE_MSG"
   "<TASK_INFO>"
   "TASK_INFO"
   "<USV_POSE_MSG>"
   "USV_POSE_MSG"
   "<ZED2I_MSG>"
   "ZED2I_MSG"
  ))

