// Generated by gencpp from file jetson/state_msg.msg
// DO NOT EDIT!


#ifndef JETSON_MESSAGE_STATE_MSG_H
#define JETSON_MESSAGE_STATE_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Int32.h>

namespace jetson
{
template <class ContainerAllocator>
struct state_msg_
{
  typedef state_msg_<ContainerAllocator> Type;

  state_msg_()
    : header()
    , state()  {
    }
  state_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::jetson::state_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetson::state_msg_<ContainerAllocator> const> ConstPtr;

}; // struct state_msg_

typedef ::jetson::state_msg_<std::allocator<void> > state_msg;

typedef boost::shared_ptr< ::jetson::state_msg > state_msgPtr;
typedef boost::shared_ptr< ::jetson::state_msg const> state_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetson::state_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetson::state_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetson::state_msg_<ContainerAllocator1> & lhs, const ::jetson::state_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetson::state_msg_<ContainerAllocator1> & lhs, const ::jetson::state_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetson

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetson::state_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetson::state_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetson::state_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetson::state_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetson::state_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetson::state_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetson::state_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3471e556b0d295809f9950ffc322ab3d";
  }

  static const char* value(const ::jetson::state_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3471e556b0d29580ULL;
  static const uint64_t static_value2 = 0x9f9950ffc322ab3dULL;
};

template<class ContainerAllocator>
struct DataType< ::jetson::state_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetson/state_msg";
  }

  static const char* value(const ::jetson::state_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetson::state_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/Int32 state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
;
  }

  static const char* value(const ::jetson::state_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetson::state_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetson::state_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetson::state_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETSON_MESSAGE_STATE_MSG_H
