// Generated by gencpp from file amore/my_msg.msg
// DO NOT EDIT!


#ifndef AMORE_MESSAGE_MY_MSG_H
#define AMORE_MESSAGE_MY_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace amore
{
template <class ContainerAllocator>
struct my_msg_
{
  typedef my_msg_<ContainerAllocator> Type;

  my_msg_()
    : points()
    , psi(0.0)  {
    }
  my_msg_(const ContainerAllocator& _alloc)
    : points(_alloc)
    , psi(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;

   typedef double _psi_type;
  _psi_type psi;





  typedef boost::shared_ptr< ::amore::my_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amore::my_msg_<ContainerAllocator> const> ConstPtr;

}; // struct my_msg_

typedef ::amore::my_msg_<std::allocator<void> > my_msg;

typedef boost::shared_ptr< ::amore::my_msg > my_msgPtr;
typedef boost::shared_ptr< ::amore::my_msg const> my_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amore::my_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amore::my_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amore::my_msg_<ContainerAllocator1> & lhs, const ::amore::my_msg_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points &&
    lhs.psi == rhs.psi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amore::my_msg_<ContainerAllocator1> & lhs, const ::amore::my_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amore

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::amore::my_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore::my_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore::my_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore::my_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore::my_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore::my_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amore::my_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64555233587211f62e3a55ce9242df37";
  }

  static const char* value(const ::amore::my_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64555233587211f6ULL;
  static const uint64_t static_value2 = 0x2e3a55ce9242df37ULL;
};

template<class ContainerAllocator>
struct DataType< ::amore::my_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amore/my_msg";
  }

  static const char* value(const ::amore::my_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amore::my_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] points\n"
"float64 psi\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::amore::my_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amore::my_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
      stream.next(m.psi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amore::my_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amore::my_msg_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMORE_MESSAGE_MY_MSG_H
