// Generated by gencpp from file amore/usv_pose_msg.msg
// DO NOT EDIT!


#ifndef AMORE_MESSAGE_USV_POSE_MSG_H
#define AMORE_MESSAGE_USV_POSE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace amore
{
template <class ContainerAllocator>
struct usv_pose_msg_
{
  typedef usv_pose_msg_<ContainerAllocator> Type;

  usv_pose_msg_()
    : header()
    , position()
    , psi()
    , latitude()
    , longitude()  {
    }
  usv_pose_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , psi(_alloc)
    , latitude(_alloc)
    , longitude(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _psi_type;
  _psi_type psi;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _latitude_type;
  _latitude_type latitude;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _longitude_type;
  _longitude_type longitude;





  typedef boost::shared_ptr< ::amore::usv_pose_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amore::usv_pose_msg_<ContainerAllocator> const> ConstPtr;

}; // struct usv_pose_msg_

typedef ::amore::usv_pose_msg_<std::allocator<void> > usv_pose_msg;

typedef boost::shared_ptr< ::amore::usv_pose_msg > usv_pose_msgPtr;
typedef boost::shared_ptr< ::amore::usv_pose_msg const> usv_pose_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amore::usv_pose_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amore::usv_pose_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amore::usv_pose_msg_<ContainerAllocator1> & lhs, const ::amore::usv_pose_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.psi == rhs.psi &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amore::usv_pose_msg_<ContainerAllocator1> & lhs, const ::amore::usv_pose_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amore

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::amore::usv_pose_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore::usv_pose_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore::usv_pose_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore::usv_pose_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore::usv_pose_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore::usv_pose_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amore::usv_pose_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec83d6a1d1a8805fa2cb78e46565b333";
  }

  static const char* value(const ::amore::usv_pose_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec83d6a1d1a8805fULL;
  static const uint64_t static_value2 = 0xa2cb78e46565b333ULL;
};

template<class ContainerAllocator>
struct DataType< ::amore::usv_pose_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amore/usv_pose_msg";
  }

  static const char* value(const ::amore::usv_pose_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amore::usv_pose_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point position\n"
"std_msgs/Float64 psi\n"
"std_msgs/Float64 latitude\n"
"std_msgs/Float64 longitude\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::amore::usv_pose_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amore::usv_pose_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.psi);
      stream.next(m.latitude);
      stream.next(m.longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct usv_pose_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amore::usv_pose_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amore::usv_pose_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "psi: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.psi);
    s << indent << "latitude: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMORE_MESSAGE_USV_POSE_MSG_H
